### ISSUE TITLE
On failed refresh error details are not displayed

### ISSUE THREAD

**Issue by riesvriend** [ServiceStack/ServiceStackVS#27] opened 2016-05-06 14:38 UTC
The ServiceStackVS output pane displays the following error when I refresh the TypeScript service reference 'ServiceFlow.dtos.d.ts' that is part of my project:

--- Updating ServiceStack Reference 'ServiceFlow.dtos.d.ts' ---
Failed to update ServiceStack Reference: Unhandled error - The remote server returned an error: (500) Internal Server Error.
--- Update ServiceStack Reference Complete ---

This was working on this project a few days ago, must have made a few changes that caused this bug.
It would be a great help to have the full exception dump available. Will post an update if I find the cause myself.

**Comment by riesvriend** [comment] 2016-05-06 14:51
Found the cause by rollback change sets: I had a request/response DTO pair that was not in a C# namespace. Still it would be nice to know how to get a helpful error message in a case like this.

**Comment by Layoric** [comment] 2016-05-07 09:42
@riesvriend Thanks for reporting the issue, it looks like you might have hit a bug with the TypeScript reference generation, so I'm not sure how much info you would have gotten a part from Internal Server Error. The only part we are not showing is the HTTP error code.

Could you please let me know a few more details so I know I can reproduce the issue? For example?

ServiceStack version: (eg, 4.0.56)
Visual Studio version
OS version

Also any code required to reproduce the issue? I think I'm reproducing your issue with 4.0.56 and the following. Is that right?

``` CSharp
[Route("/foo")]
public class ClassCausingTheIssue
{
    public string Id { get; set; }
}
namespace MyApp.ServiceModel
{
    [Route("/hello")]
    [Route("/hello/{Name}")]
    public class Hello : IReturn<HelloResponse>
    {
        public string Name { get; set; }
    }
}
```

Since the code is generated on the server and this is a bug, it's not something the server can give any more info about. The Add ServiceStack Reference add or update is simply calling the appropriate `/types` path for a specified language. For example, `/types/typescript`. 

Currently looking into the issue and I'll keep you posted here with any updates.

**Comment by riesvriend** [comment] 2016-05-07 10:51
Your scenario is correct. ServiceStack version 4.0.54, ServiceStackVS extension 1.0.24. VS.NET 2015 Update 2.
Thanks

**Comment by Layoric** [comment] 2016-05-07 11:24
Thanks for all the details. Yeah, it looks like it was a missed NRE in the TypeScript generation. 

Should be fixed in [this commit](https://github.com/ServiceStack/ServiceStack/pull/1028/commits/1e1bae80d39817ed7093bfda5b68489c1ca2f800) and available on the next push to MyGet. I'd suggest declaring DTOs within namespaces anyway, but after the fix, it will just add the request/response object into the default TypeScript module. 

Thanks for reporting the issue :+1:

**Comment by Layoric** [comment] 2016-05-12 03:27
@riesvriend updates, include fix related to this issue have been pushed and now available from MyGet, closing issue. Open a new issue if you find you are having any other problems :+1:

**Closed by Layoric** 2016-05-12 03:27 UTC
